# Generated by Django 5.2.7 on 2025-10-30 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFicticiosEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=100)),
                ('alunos_previstos_2023', models.IntegerField(blank=True, null=True)),
                ('percentual_peso', models.FloatField(blank=True, null=True)),
                ('saepe_2022', models.FloatField(blank=True, null=True)),
                ('saepe_2023', models.FloatField(blank=True, null=True)),
                ('proficiencia_lp_2023', models.FloatField(blank=True, null=True)),
                ('proficiencia_mt_2023', models.FloatField(blank=True, null=True)),
                ('matricula_efaf_2024', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=255)),
                ('data_visita', models.DateField(blank=True, null=True)),
                ('tecnico_gre', models.CharField(blank=True, max_length=255, null=True)),
                ('servidor_escola', models.CharField(blank=True, max_length=255, null=True)),
                ('demanda', models.TextField(blank=True, null=True)),
                ('encaminhamento', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes da visita')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
                ('ocorrencias', models.ManyToManyField(to='core.ocorrencia')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebido_por', models.CharField(blank=True, max_length=200, verbose_name='Recebido por')),
                ('data_visita', models.DateField(verbose_name='Data da visita')),
                ('hora_visita', models.TimeField(blank=True, null=True, verbose_name='Horário da visita')),
                ('objetivo', models.CharField(blank=True, max_length=300, verbose_name='Objetivo da visita')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada')], default='realizada', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.escola')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data_visita', '-hora_visita'],
            },
        ),
    ]
