# Generated by Django 5.2.7 on 2025-10-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada')], default='realizada', max_length=10),
        ),
        migrations.AlterField(
            model_name='visita',
            name='recebido_por',
            field=models.CharField(blank=True, max_length=200, verbose_name='Recebido por'),
        ),
    ]
