# Generated by Django 5.2.1 on 2025-10-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_visita_status_alter_visita_recebido_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFicticiosEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=255)),
                ('modalidade', models.CharField(max_length=100)),
                ('alunos_previstos_2023', models.IntegerField(blank=True, null=True)),
                ('percentual_peso', models.FloatField(blank=True, null=True)),
                ('saepe_2022', models.FloatField(blank=True, null=True)),
                ('saepe_2023', models.FloatField(blank=True, null=True)),
                ('proficiencia_lp_2023', models.FloatField(blank=True, null=True)),
                ('proficiencia_mt_2023', models.FloatField(blank=True, null=True)),
                ('matricula_efaf_2024', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
