# Generated by Django 5.2.1 on 2025-10-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dadosficticiosescola'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=255)),
                ('data_visita', models.DateField(blank=True, null=True)),
                ('tecnico_gre', models.CharField(blank=True, max_length=255, null=True)),
                ('servidor_escola', models.CharField(blank=True, max_length=255, null=True)),
                ('demanda', models.TextField(blank=True, null=True)),
                ('encaminhamento', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
