# Generated by Django 4.2.16 on 2025-11-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visitatecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitatecnica',
            name='ocorrencias',
            field=models.ManyToManyField(blank=True, to='core.ocorrencia', verbose_name='Ocorrências observadas'),
        ),
    ]
